FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY logo.png /usr/share/nginx/html/logo.png
COPY favicon-32.png /usr/share/nginx/html/favicon-32.png
COPY apple-touch-icon.png /usr/share/nginx/html/apple-touch-icon.png
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3001
